# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu", primary: true do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-16.04"
    ubuntu.vm.network "private_network", ip: "192.168.60.10"
    ubuntu.vm.synced_folder File.dirname(__FILE__), "/vagrant"
    ubuntu.vm.synced_folder "../audioreg-admin-app", "/var/www/audioreg-admin-app", create: true, group: "www-data", owner: "www-data"
    ubuntu.vm.synced_folder "../audioreg-client-main", "/var/www/audioreg-client-main", create: true, group: "www-data", owner: "www-data"
    ubuntu.vm.synced_folder "../audioreg-internal-api", "/var/www/audioreg-internal-api", create: true, group: "www-data", owner: "www-data"
    ubuntu.vm.provision "shell", path: "provision/local/setup.sh"
    ubuntu.vm.provider "virtualbox" do |v|
      v.name = "audioreg"
      v.memory = 1332
    end
  end

end